doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_mysql'
        server_version: '10.11.2-MariaDB'
        charset: utf8mb4
        default_table_options:
          charset: utf8mb4
          collate: utf8mb4_unicode_ci
          engine: InnoDB

      sphinx:
        url: 'mysql://root:@%env(SPHINX_HOST)%:%env(SPHINX_PORT)%/'
        driver: 'pdo_mysql'

  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        type: attribute
        is_bundle: false
        dir: '%kernel.project_dir%/src/Domain/Entity'
        prefix: 'App\Domain\Entity'
        alias: App

doctrine_migrations:
  migrations_paths:
    'DoctrineMigrations': '%kernel.project_dir%/migrations'
  storage:
    table_storage:
      table_name: 'doctrine_migration_versions'
